# -*- coding: utf-8 -*-
"""scientific_g2p.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZj22MNBi8BTzaENGnI7Ab76FnwBXVjI

# Scientific G2P: Transfer Learning for Scientific Text-to-Speech

This notebook replicates and extends the approach from:
> *Grapheme-to-Phoneme Transformer Model for Transfer Learning Dialects* (Engelhart et al., 2021)

...applied to **scientific vocabulary** (general science, chemistry, physics/maths).

### What we're doing
A **Grapheme-to-Phoneme (G2P)** model converts written text into phonetic symbols — e.g. `science → ˈsaɪəns`. This is a critical component of any Text-to-Speech (TTS) pipeline, because TTS systems need to know *how to say* a word, not just how to spell it.

Scientific words are hard for standard G2P models because they follow different pronunciation rules (Latin/Greek roots, IUPAC conventions). We solve this by:
1. **Pretraining** a transformer model on general English (CMUDict)
2. **Fine-tuning** it on a scientific pronunciation dictionary we build here

### Pipeline overview
```
Section 1: Install dependencies
Section 2: Build scientific pronunciation dictionary (eSpeak-NG → IPA)
Section 3: Build sentence corpus (arXiv abstracts)
Section 4: Prepare datasets
Section 5: Define the Transformer model (PyTorch)
Section 6: Pretrain on CMUDict (American English)
Section 7: Fine-tune on scientific dictionary
Section 8: Evaluate (Phoneme Error Rate)
Section 9: Test on example scientific sentences
```

---
⚠️ **Runtime**: Set your Colab runtime to **GPU** (Runtime → Change runtime type → T4 GPU) before running.

## Section 1: Install Dependencies
"""

# Install system-level dependencies first
# eSpeak-NG is a rule-based speech synthesizer that can output IPA.
# It handles scientific/technical words better than purely learned G2P systems.
#!apt-get install -y espeak-ng espeak-ng-data libespeak-ng-dev

# Python packages
#!pip install -q \
#    phonemizer \
#    datasets \
#    arxiv \
#    nltk \
#    jiwer \
#    tqdm \
#    matplotlib \
#    pandas

# phonemizer wraps eSpeak-NG in a clean Python API
# datasets gives us easy access to HuggingFace datasets (we use it for LibriTTS text)
# arxiv lets us pull abstracts programmatically
# jiwer computes error rates (we adapt it for phonemes)

import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
print("✓ All dependencies installed")

import os, json, re, math, random, time
from pathlib import Path
from collections import Counter
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from phonemizer import phonemize
from phonemizer.backend import EspeakBackend

# Reproducibility — same seed as the paper
SEED = 1234
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"✓ Using device: {DEVICE}")
if DEVICE.type == 'cpu':
    print("  ⚠️  No GPU detected — training will be slow. Check Runtime → Change runtime type → T4 GPU")

"""## Section 2: Build the Scientific Pronunciation Dictionary

This is the most important — and most effortful — part of the project.

**The approach:**
1. Collect scientific terms from multiple sources
2. Use eSpeak-NG to automatically generate IPA pronunciations (this gives us *noisy* labels)
3. Save the dictionary so you can manually correct entries later

**Important caveat:** eSpeak-NG's pronunciations for scientific terms are imperfect. For a prototype this is fine. For a publication-quality system, you would want to manually verify at least a few hundred entries — especially IUPAC chemistry names.
"""

from phonemizer import phonemize
from phonemizer.backend import EspeakBackend
from phonemizer.separator import Separator   # ← add this

test_words = [
    "photosynthesis",
    "eigenvalue",
    "methylpropanol",
    "neutrino",
    "heliocentric",
    "deoxyribonucleic",
    "thermodynamics",
]

backend = EspeakBackend('en-us', with_stress=True)
ipa_results = backend.phonemize(
    test_words,
    separator=Separator(word=' ', phone='|')   # ← use imported class directly
)

print("Word → IPA (eSpeak-NG, en-us)")
print("-" * 45)
for word, ipa in zip(test_words, ipa_results):
    print(f"{word:<25} → {ipa}")

# --- SCIENTIFIC TERM SOURCES ---
#
# We combine several sources to get a broad scientific vocabulary:
#   A) A curated seed list of common scientific terms (provided here)
#   B) Terms extracted from arXiv abstracts (automated)
#   C) Any custom words you want to add (edit the list below)
#
# The paper used ~1K-10K words for fine-tuning. We aim for a similar range.

# A) Curated seed scientific vocabulary
# These are high-frequency terms across general science, chemistry, physics/maths
# Extend this list with domain-specific terms relevant to your TTS use case

SEED_SCIENTIFIC_TERMS = [
    # General science
    "hypothesis", "empirical", "stochastic", "anisotropic", "isotropic",
    "photosynthesis", "mitochondria", "chromosome", "enzyme", "catalyst",
    "electrolysis", "osmosis", "diffusion", "viscosity", "entropy",
    "enthalpy", "exothermic", "endothermic", "stoichiometry", "equilibrium",
    "spectroscopy", "chromatography", "fluorescence", "phosphorescence",
    "electronegativity", "covalent", "ionic", "hydrogen", "nitrogen",
    "oxygen", "carbon", "helium", "argon", "chlorine", "fluorine",
    "magnesium", "potassium", "calcium", "silicon", "phosphorus",
    "titanium", "vanadium", "chromium", "manganese", "cobalt",
    "nickel", "copper", "zinc", "gallium", "germanium", "arsenic",
    "selenium", "bromine", "rubidium", "strontium", "zirconium",
    "molybdenum", "technetium", "ruthenium", "rhodium", "palladium",
    "cadmium", "indium", "antimony", "tellurium", "caesium", "barium",
    "lanthanum", "cerium", "praseodymium", "neodymium", "promethium",
    "samarium", "europium", "gadolinium", "terbium", "dysprosium",
    "holmium", "erbium", "thulium", "ytterbium", "lutetium",
    "hafnium", "tantalum", "tungsten", "rhenium", "osmium", "iridium",
    "platinum", "mercury", "thallium", "bismuth", "polonium",
    "astatine", "francium", "radium", "actinium", "thorium",
    "protactinium", "uranium", "neptunium", "plutonium", "americium",
    "berkelium", "californium",
    # Physics / maths
    "eigenvalue", "eigenvector", "hamiltonian", "lagrangian", "tensor",
    "fourier", "laplacian", "gradient", "divergence", "curl",
    "differential", "integral", "derivative", "polynomial", "eigenfunction",
    "thermodynamics", "electromagnetism", "photoelectric", "quanta",
    "neutrino", "boson", "fermion", "hadron", "lepton", "quark",
    "photon", "graviton", "muon", "pion", "kaon", "meson",
    "superconductivity", "semiconductor", "piezoelectric", "ferromagnetic",
    "paramagnetic", "diamagnetic", "heliocentric", "geocentric",
    "parallax", "parsec", "redshift", "blueshift", "spectral",
    "hertz", "joule", "pascal", "coulomb", "farad", "henry",
    "siemens", "weber", "tesla", "becquerel", "sievert", "kelvin",
    "boltzmann", "planck", "avogadro", "lorentz", "schrodinger",
    "heisenberg", "feynman",
    # Chemistry / IUPAC
    "methane", "ethane", "propane", "butane", "pentane", "hexane",
    "heptane", "octane", "nonane", "decane", "ethylene", "propylene",
    "acetylene", "benzene", "toluene", "xylene", "styrene", "phenol",
    "methanol", "ethanol", "propanol", "butanol", "glycerol",
    "acetone", "aldehyde", "ketone", "carboxyl", "amine", "amide",
    "ester", "ether", "anhydride", "nitrile", "sulfide", "sulfate",
    "nitrate", "phosphate", "carbonate", "bicarbonate", "hydroxide",
    "deoxyribonucleic", "ribonucleic", "nucleotide", "nucleoside",
    "adenine", "guanine", "cytosine", "thymine", "uracil",
    "glucose", "fructose", "sucrose", "lactose", "maltose",
    "polysaccharide", "monosaccharide", "disaccharide",
    "amino", "glycine", "alanine", "valine", "leucine", "isoleucine",
    "proline", "phenylalanine", "tryptophan", "methionine", "serine",
    "threonine", "cysteine", "tyrosine", "asparagine", "glutamine",
    "aspartate", "glutamate", "lysine", "arginine", "histidine",
    # Longer / harder IUPAC-style words
    "methylpropanol", "dimethylsulfoxide", "tetrahydrofuran",
    "dichloromethane", "trifluoromethane", "acetonitrile",
    "diethylether", "triethylamine", "pyridine", "imidazole",
    "morpholine", "piperidine", "quinoline", "isoquinoline",
    "naphthalen", "anthracene", "pyrene", "perylene",
]

# C) Add your own domain-specific terms here:
CUSTOM_TERMS = [
    # e.g. "crispr", "nanoparticle", "electroencephalogram"
]

ALL_TERMS = list(set([t.lower() for t in SEED_SCIENTIFIC_TERMS + CUSTOM_TERMS]))
print(f"✓ Seed vocabulary size: {len(ALL_TERMS)} unique terms")

# Extract additional scientific terms from arXiv abstracts
# We fetch abstracts from physics, chemistry, and math categories
# and extract long words (>8 chars) as candidate scientific terms

import arxiv

def fetch_arxiv_terms(queries, max_results_per_query=50, min_word_length=9,
                      per_query_timeout=30):
    """Fetch arXiv abstracts and extract long, unusual words as scientific term candidates.

    per_query_timeout: seconds to wait per query before giving up (default 30).
    If a query times out or fails it is skipped — the seed vocabulary is used instead.
    """
    import concurrent.futures

    candidate_terms = set()
    abstracts = []

    def _fetch_one(query):
        """Fetch abstracts for a single query. Runs in a thread so it can be timed out."""
        results = []
        client = arxiv.Client()
        search = arxiv.Search(
            query=query,
            max_results=max_results_per_query,
            sort_by=arxiv.SortCriterion.Relevance,
        )
        for result in client.results(search):
            results.append(result.summary)
        return results

    for query in queries:
        print(f"  Querying arXiv: '{query}' ...", end="", flush=True)
        try:
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                future = ex.submit(_fetch_one, query)
                results = future.result(timeout=per_query_timeout)
            abstracts.extend(results)
            print(f" {len(results)} abstracts")
        except concurrent.futures.TimeoutError:
            print(f" timed out after {per_query_timeout}s — skipping")
        except Exception as e:
            print(f" failed ({e}) — skipping")

    print(f"  Fetched {len(abstracts)} abstracts total")

    for abstract in abstracts:
        words = re.findall(r'[a-zA-Z]+', abstract)
        for w in words:
            if len(w) >= min_word_length:
                candidate_terms.add(w.lower())

    return list(candidate_terms), abstracts

print("Fetching arXiv abstracts (this may take a minute)...")
arxiv_queries = [
    "chemistry molecular synthesis",
    "quantum physics thermodynamics",
    "mathematics differential equations",
    "biochemistry protein structure",
]

arxiv_terms, arxiv_abstracts = fetch_arxiv_terms(arxiv_queries, max_results_per_query=30)
print(f"✓ Extracted {len(arxiv_terms)} candidate terms from arXiv")

# Combine all terms
ALL_TERMS = list(set(ALL_TERMS + arxiv_terms))
print(f"✓ Total vocabulary (before filtering): {len(ALL_TERMS)} unique terms")

# Generate IPA pronunciations for all terms using eSpeak-NG
# This is the automated (noisy) annotation step

def generate_ipa_dictionary(terms, language='en-us', batch_size=100):
    """
    Generate IPA pronunciations for a list of words using eSpeak-NG.
    Returns a dict: {word: ipa_string}
    Filters out words where eSpeak-NG returns empty or suspicious results.
    """
    backend = EspeakBackend(language, with_stress=True)
    sep = Separator(word=' ', phone='|')

    dictionary = {}
    failed = []

    # Process in batches to avoid memory issues
    for i in tqdm(range(0, len(terms), batch_size), desc="Generating IPA"):
        batch = terms[i:i+batch_size]
        try:
            ipa_batch = backend.phonemize(batch, separator=sep)
            for word, ipa in zip(batch, ipa_batch):
                ipa_clean = ipa.strip()
                # Filter: skip if IPA is empty or suspiciously short for the word
                if ipa_clean and len(ipa_clean) >= 2:
                    # Convert | separators to spaces for phoneme sequences
                    phoneme_seq = ' '.join(ipa_clean.replace('|', ' ').split())
                    dictionary[word] = phoneme_seq
                else:
                    failed.append(word)
        except Exception as e:
            failed.extend(batch)

    print(f"✓ Dictionary built: {len(dictionary)} entries, {len(failed)} failed")
    return dictionary, failed

import phonemizer

# Save the dictionary to disk if it was newly generated
#
# IMPORTANT: For a production system, open scientific_dictionary.json and
# manually correct pronunciations for the most important/frequent terms.
# eSpeak-NG is good but not perfect for technical vocabulary.

# Check if the file exists
Path('data').mkdir(exist_ok=True)
sci_dictionary_path = 'data/scientific_dictionary.json'
sci_dictionary_exists_on_disk = os.path.exists(sci_dictionary_path)

if not sci_dictionary_exists_on_disk:
    print("Generating new scientific dictionary with eSpeak-NG...")
    sci_dictionary, failed_words = generate_ipa_dictionary(ALL_TERMS)

    # Preview a sample if newly generated
    print("\nSample entries from newly generated dictionary:")
    for word in list(sci_dictionary.keys())[:10]:
        print(f"  {word:<30} → {sci_dictionary[word]}")
    with open('data/scientific_dictionary.json', 'w') as f:
        json.dump(sci_dictionary, f, indent=2, ensure_ascii=False)
    print(f"✓ Newly generated dictionary saved to data/scientific_dictionary.json")
    print(f"  → Review and correct this file before training for best results")
else:
    with open(sci_dictionary_path, 'r') as f:
        sci_dictionary = json.load(f)
    print(f"✓ Loaded {len(sci_dictionary)} entries from {sci_dictionary_path}")

# Convert keys to lowercase to ensure consistency with how terms are extracted and processed.
# This prevents issues where 'Word' might not match 'word' if manually edited.
sci_dictionary = {k.lower(): v for k, v in sci_dictionary.items()}
print("  (All keys converted to lowercase)")

"""## Section 3: Build the CMUDict (Source) and Sentence Corpora

Following the paper exactly:
- We pretrain on **CMUDict** (general American English) — our "source dialect"
- We use **LibriTTS** sentence text to generate sentence-level training pairs
- Then we fine-tune using scientific terms inserted into sentences
"""

# Download CMUDict — the standard American English pronunciation dictionary
# ~134K words with ARPAbet phonemes. We convert these to IPA so both
# source and target use the same phoneme representation.

import urllib.request

CMUDICT_URL = "https://raw.githubusercontent.com/cmusphinx/cmudict/master/cmudict.dict"
CMUDICT_PATH = "data/cmudict.dict"

if not os.path.exists(CMUDICT_PATH):
    print("Downloading CMUDict...")
    urllib.request.urlretrieve(CMUDICT_URL, CMUDICT_PATH)
    print("✓ CMUDict downloaded")
else:
    print("✓ CMUDict already present")

# Parse CMUDict — take first pronunciation for words with multiple
def load_cmudict(path):
    dictionary = {}
    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith(';;;'):
                continue
            parts = line.split()
            word = parts[0].lower()
            # Skip alternate pronunciations (CMUDict marks them as word(2), word(3))
            if '(' in word:
                continue
            phonemes = ' '.join(parts[1:])
            if word not in dictionary:  # keep first pronunciation only
                dictionary[word] = phonemes
    return dictionary

cmu_dict_raw = load_cmudict(CMUDICT_PATH)
print(f"✓ CMUDict loaded: {len(cmu_dict_raw)} entries (ARPAbet)")

# Convert CMUDict ARPAbet → IPA so we have a unified phoneme set
# We use eSpeak-NG to re-generate IPA for CMUDict words.
# This is cleaner than maintaining a manual ARPAbet→IPA mapping.
#
# Note: we only do this for a subset (50K words) to keep runtime manageable.
# The paper used ~130K words for pretraining; for a prototype 50K is fine.

PRETRAIN_VOCAB_SIZE = 50000  # reduce to 20000 if this is too slow

# Sort by word frequency (common words first) using word length as proxy
# In a production system you'd sort by corpus frequency
cmu_words = sorted(cmu_dict_raw.keys(), key=len)[:PRETRAIN_VOCAB_SIZE]

print(f"Generating IPA for {len(cmu_words)} CMUDict words (this will take several minutes)...")
cmu_ipa_dict, cmu_failed = generate_ipa_dictionary(cmu_words, language='en-us')

with open('data/cmudict_ipa.json', 'w') as f:
    json.dump(cmu_ipa_dict, f, ensure_ascii=False)

print(f"✓ CMUDict IPA dictionary: {len(cmu_ipa_dict)} entries")

# Build sentence-level training data
# The paper uses LibriTTS sentences as the sentence source, then looks up
# each word in the dictionary to create (sentence, phoneme_sequence) pairs.
# We do the same, using arXiv abstracts for scientific fine-tuning data.

import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

def build_sentence_pairs(sentences, word_dictionary, min_coverage=0.85):
    """
    Convert sentences to (grapheme_sentence, phoneme_sentence) pairs.
    Only includes words that appear in the dictionary — skips unknown words
    in both the grapheme AND phoneme sequence so they stay aligned.
    """
    pairs = []
    dict_words = set(word_dictionary.keys())

    for sent in tqdm(sentences, desc="Building pairs"):
        sent = sent.strip().lower()
        words = [w for w in re.findall(r'[a-zA-Z]+', sent) if w]
        if not words or len(words) < 3:
            continue

        covered = [w for w in words if w in dict_words]
        if len(covered) / len(words) < min_coverage:
            continue

        # Only include words that are in the dictionary (keeps G/P aligned)
        grapheme_parts = []
        phoneme_parts  = []
        for w in words:
            if w in word_dictionary:
                grapheme_parts.append(w)
                phoneme_parts.append(word_dictionary[w])

        if len(grapheme_parts) >= 3:  # skip if too few words survive
            pairs.append((' '.join(grapheme_parts), ' | '.join(phoneme_parts)))

    return pairs

from datasets import load_dataset

print("Loading LibriSpeech LM text corpus...")
import urllib.request

LM_TEXT_URL = "https://www.openslr.org/resources/11/librispeech-lm-norm.txt.gz"
LM_PATH = "data/librispeech_lm.txt.gz"

if not os.path.exists(LM_PATH):
    print("  Downloading (~120MB, may take a minute)...")
    urllib.request.urlretrieve(LM_TEXT_URL, LM_PATH)

import gzip
libritts_sentences = []
with gzip.open(LM_PATH, 'rt', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= 500000:  # take first 500K lines
            break
        line = line.strip()
        if line:
            libritts_sentences.append(line)

# Filter by length (remove top/bottom 3% as per paper)
lengths = [len(s) for s in libritts_sentences]
low, high = np.percentile(lengths, 3), np.percentile(lengths, 97)
libritts_sentences = [s for s in libritts_sentences if low <= len(s) <= high]
print(f"✓ LibriSpeech LM sentences: {len(libritts_sentences)}")

# Then continue as before...
print("\nBuilding CMUDict pretraining pairs...")
pretrain_pairs = build_sentence_pairs(libritts_sentences, cmu_ipa_dict, min_coverage=0.95)
print(f"✓ Pretrain pairs: {len(pretrain_pairs)}")

# Rebuild all_sentences from arxiv_abstracts
all_sentences = []
for abstract in arxiv_abstracts:
    all_sentences.extend(sent_tokenize(abstract))

print(f"arxiv_abstracts: {len(arxiv_abstracts)}")
print(f"all_sentences before filter: {len(all_sentences)}")

if len(all_sentences) == 0:
    print("⚠️  arxiv_abstracts is empty — re-fetching...")
    arxiv_queries = [
        "chemistry molecular synthesis",
        "quantum physics thermodynamics",
        "mathematics differential equations",
        "biochemistry protein structure",
    ]
    _, arxiv_abstracts = fetch_arxiv_terms(arxiv_queries, max_results_per_query=30)
    for abstract in arxiv_abstracts:
        all_sentences.extend(sent_tokenize(abstract))
    print(f"  Re-fetched {len(arxiv_abstracts)} abstracts → {len(all_sentences)} sentences")

# Filter by length only if we have sentences
if len(all_sentences) > 0:
    lengths = [len(s) for s in all_sentences]
    low, high = np.percentile(lengths, 3), np.percentile(lengths, 97)
    all_sentences = [s for s in all_sentences if low <= len(s) <= high]
    print(f"✓ arXiv sentences after filter: {len(all_sentences)}")
else:
    print("❌ Could not retrieve any sentences — check your internet connection")

print("\nBuilding scientific fine-tuning pairs from arXiv...")
combined_dict = {**cmu_ipa_dict, **sci_dictionary}
# ... rest of the cell continues as before

print("\nBuilding scientific fine-tuning pairs from arXiv...")
combined_dict = {**cmu_ipa_dict, **sci_dictionary}
sci_pairs = build_sentence_pairs(all_sentences, combined_dict, min_coverage=0.80)
sci_words_set = set(sci_dictionary.keys())
sci_pairs = [
    (g, p) for g, p in sci_pairs
    if any(w in sci_words_set for w in g.split())
]
print(f"✓ Scientific pairs: {len(sci_pairs)}")

"""## Section 4: Prepare Datasets and Vocabulary"""

# Build character and phoneme vocabularies
#
# The model treats G2P as sequence-to-sequence:
#   INPUT:  character sequence  e.g. ['p','h','o','t','o','s','y','n','t','h','e','s','i','s']
#   OUTPUT: phoneme sequence    e.g. ['f','oʊ','t','oʊ','s','ɪ','n','θ','ə','s','ɪ','s']
#
# Special tokens:
#   <pad>  — padding to fixed length
#   <sos>  — start of sequence (decoder input)
#   <eos>  — end of sequence
#   <unk>  — unknown token

SPECIAL_TOKENS = ['<pad>', '<sos>', '<eos>', '<unk>']
PAD_IDX, SOS_IDX, EOS_IDX, UNK_IDX = 0, 1, 2, 3

def build_vocab(pairs, mode='char'):
    """Build vocabulary from (grapheme, phoneme) pairs.
    mode='char' for grapheme vocab, mode='phoneme' for phoneme vocab.
    """
    tokens = set()
    for grapheme, phoneme in pairs:
        if mode == 'char':
            tokens.update(list(grapheme))  # character-level
        else:
            tokens.update(phoneme.split())  # space-separated phonemes
    vocab = SPECIAL_TOKENS + sorted(tokens)
    token2idx = {t: i for i, t in enumerate(vocab)}
    idx2token = {i: t for t, i in token2idx.items()}
    return vocab, token2idx, idx2token

# Build from all available data (pretrain + fine-tune)
all_pairs = pretrain_pairs + sci_pairs

char_vocab, char2idx, idx2char = build_vocab(all_pairs, mode='char')
phoneme_vocab, phoneme2idx, idx2phoneme = build_vocab(all_pairs, mode='phoneme')

print(f"✓ Character vocabulary: {len(char_vocab)} tokens")
print(f"✓ Phoneme vocabulary:   {len(phoneme_vocab)} tokens")
print(f"   Sample chars:   {char_vocab[4:20]}")
print(f"   Sample phonemes:{phoneme_vocab[4:20]}")

# Save vocabularies
with open('data/char_vocab.json', 'w') as f:
    json.dump({'vocab': char_vocab, 'token2idx': char2idx}, f)
with open('data/phoneme_vocab.json', 'w') as f:
    json.dump({'vocab': phoneme_vocab, 'token2idx': phoneme2idx}, f)
print("✓ Vocabularies saved")

print(f"pretrain_pairs: {len(pretrain_pairs)}")
print(f"sci_pairs:      {len(sci_pairs)}")
print(f"all_sentences:  {len(all_sentences)}")
print(f"cmu_ipa_dict:   {len(cmu_ipa_dict)} words")
print(f"sci_dictionary: {len(sci_dictionary)} words")

# Check a few sentences to see what's failing coverage
sample = all_sentences[:5]
for s in sample:
    words = [w for w in re.findall(r'[a-zA-Z]+', s.lower()) if w]
    covered = [w for w in words if w in cmu_ipa_dict]
    print(f"\n  Sentence: {s[:60]}...")
    print(f"  Words: {len(words)}, Covered: {len(covered)}, Rate: {len(covered)/max(len(words),1):.2f}")

# Split into train/validation/test sets and create PyTorch Dataset

MAX_SEQ_LEN = 240  # same as the paper

def encode_pair(grapheme, phoneme, char2idx, phoneme2idx, max_len=MAX_SEQ_LEN):
    """Convert a (grapheme, phoneme) string pair to integer index tensors."""
    # Grapheme: character by character
    g_ids = [char2idx.get(c, UNK_IDX) for c in grapheme][:max_len-2]
    g_ids = [SOS_IDX] + g_ids + [EOS_IDX]

    # Phoneme: token by token (space-separated)
    p_ids = [phoneme2idx.get(p, UNK_IDX) for p in phoneme.split()][:max_len-2]
    p_ids = [SOS_IDX] + p_ids + [EOS_IDX]

    return g_ids, p_ids


class G2PDataset(Dataset):
    def __init__(self, pairs, char2idx, phoneme2idx, max_len=MAX_SEQ_LEN):
        self.samples = []
        for g, p in pairs:
            g_ids, p_ids = encode_pair(g, p, char2idx, phoneme2idx, max_len)
            self.samples.append((g_ids, p_ids))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]


def collate_fn(batch):
    """Pad sequences in a batch to the same length."""
    g_seqs, p_seqs = zip(*batch)
    g_lens = [len(s) for s in g_seqs]
    p_lens = [len(s) for s in p_seqs]

    g_padded = torch.zeros(len(batch), max(g_lens), dtype=torch.long)
    p_padded = torch.zeros(len(batch), max(p_lens), dtype=torch.long)

    for i, (g, p) in enumerate(zip(g_seqs, p_seqs)):
        g_padded[i, :len(g)] = torch.tensor(g)
        p_padded[i, :len(p)] = torch.tensor(p)

    return g_padded, p_padded


def split_data(pairs, train=0.8, val=0.1):
    random.shuffle(pairs)
    n = len(pairs)
    return (pairs[:int(n*train)],
            pairs[int(n*train):int(n*(train+val))],
            pairs[int(n*(train+val)):])


# Pretraining splits
pre_train, pre_val, pre_test = split_data(pretrain_pairs)
# Fine-tuning splits
ft_train, ft_val, ft_test = split_data(sci_pairs)

BATCH_SIZE = 128  # same as paper

pre_train_loader = DataLoader(G2PDataset(pre_train, char2idx, phoneme2idx),
                              batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)
pre_val_loader   = DataLoader(G2PDataset(pre_val,   char2idx, phoneme2idx),
                              batch_size=BATCH_SIZE, collate_fn=collate_fn)
ft_train_loader  = DataLoader(G2PDataset(ft_train,  char2idx, phoneme2idx),
                              batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)
ft_val_loader    = DataLoader(G2PDataset(ft_val,    char2idx, phoneme2idx),
                              batch_size=BATCH_SIZE, collate_fn=collate_fn)

print(f"✓ Pretraining:  {len(pre_train)} train / {len(pre_val)} val / {len(pre_test)} test")
print(f"✓ Fine-tuning:  {len(ft_train)} train / {len(ft_val)} val / {len(ft_test)} test")

"""## Section 5: Define the Transformer Model

We implement the same architecture as the paper:
- 3-layer Transformer encoder + 3-layer Transformer decoder
- 256-dimensional hidden states, 8 attention heads
- ~4.1M parameters
"""

class PositionalEncoding(nn.Module):
    """
    Adds positional information to token embeddings.
    Since Transformers have no built-in sense of sequence order
    (unlike RNNs), we inject position via sinusoidal encodings.
    """
    def __init__(self, d_model, dropout=0.1, max_len=512):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)  # (1, max_len, d_model)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return self.dropout(x)


class G2PTransformer(nn.Module):
    """
    Sequence-to-sequence Transformer for G2P conversion.
    Matches the architecture in Engelhart et al. (2021):
      - Encoder: character embeddings → 3-layer Transformer encoder
      - Decoder: phoneme embeddings → 3-layer Transformer decoder → FC output

    The FC output layer and phoneme embedding are re-initialised for fine-tuning
    when switching to a new phoneme set (as in the paper, Figure 1).
    """
    def __init__(self, src_vocab_size, tgt_vocab_size,
                 d_model=256, nhead=8,
                 num_encoder_layers=3, num_decoder_layers=3,
                 dim_feedforward=512, dropout=0.1):
        super().__init__()

        self.d_model = d_model

        # Encoder side: character embeddings
        self.src_embedding = nn.Embedding(src_vocab_size, d_model, padding_idx=PAD_IDX)
        self.src_pos_enc   = PositionalEncoding(d_model, dropout)

        # Decoder side: phoneme embeddings (re-initialised for transfer learning)
        self.tgt_embedding = nn.Embedding(tgt_vocab_size, d_model, padding_idx=PAD_IDX)
        self.tgt_pos_enc   = PositionalEncoding(d_model, dropout)

        # Core Transformer
        self.transformer = nn.Transformer(
            d_model=d_model,
            nhead=nhead,
            num_encoder_layers=num_encoder_layers,
            num_decoder_layers=num_decoder_layers,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True,
            norm_first=False  # Post-LN (Layer Norm), as in original Transformer
        )

        # Output projection: hidden → phoneme vocabulary (re-initialised for transfer learning)
        self.fc_out = nn.Linear(d_model, tgt_vocab_size)

        self._init_weights()

    def _init_weights(self):
        """Xavier uniform initialisation, same as the paper."""
        for p in self.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)

    def make_causal_mask(self, sz):
        """Upper-triangular mask to prevent decoder attending to future tokens."""
        return torch.triu(torch.ones(sz, sz), diagonal=1).bool().to(DEVICE)

    def encode(self, src, src_key_padding_mask=None):
        src_emb = self.src_pos_enc(self.src_embedding(src) * math.sqrt(self.d_model))
        return self.transformer.encoder(src_emb, src_key_padding_mask=src_key_padding_mask)

    def decode(self, tgt, memory, tgt_mask=None, tgt_key_padding_mask=None,
               memory_key_padding_mask=None):
        tgt_emb = self.tgt_pos_enc(self.tgt_embedding(tgt) * math.sqrt(self.d_model))
        out = self.transformer.decoder(
            tgt_emb, memory,
            tgt_mask=tgt_mask,
            tgt_key_padding_mask=tgt_key_padding_mask,
            memory_key_padding_mask=memory_key_padding_mask
        )
        return self.fc_out(out)

    def forward(self, src, tgt):
        src_pad_mask = (src == PAD_IDX)  # (B, S)
        tgt_pad_mask = (tgt == PAD_IDX)  # (B, T)
        tgt_causal   = self.make_causal_mask(tgt.size(1))

        memory = self.encode(src, src_key_padding_mask=src_pad_mask)
        logits = self.decode(tgt, memory,
                             tgt_mask=tgt_causal,
                             tgt_key_padding_mask=tgt_pad_mask,
                             memory_key_padding_mask=src_pad_mask)
        return logits  # (B, T, tgt_vocab_size)


# Instantiate model
model = G2PTransformer(
    src_vocab_size=len(char_vocab),
    tgt_vocab_size=len(phoneme_vocab),
).to(DEVICE)

n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✓ Model created: {n_params/1e6:.2f}M parameters")
print(f"   (Paper reports 4.1M — difference due to vocabulary size)")

"""## Section 6: Pretrain on CMUDict (General English)"""

def train_epoch(model, loader, optimizer, criterion, clip=1.0):
    model.train()
    total_loss = 0
    for src, tgt in loader:
        src, tgt = src.to(DEVICE), tgt.to(DEVICE)
        # Teacher forcing: decoder input is tgt[:-1], target is tgt[1:]
        tgt_in  = tgt[:, :-1]
        tgt_out = tgt[:, 1:]

        optimizer.zero_grad()
        logits = model(src, tgt_in)  # (B, T-1, vocab)

        # Flatten for cross-entropy
        loss = criterion(logits.reshape(-1, logits.size(-1)), tgt_out.reshape(-1))
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)


@torch.no_grad()
def eval_epoch(model, loader, criterion):
    model.eval()
    total_loss = 0
    for src, tgt in loader:
        src, tgt = src.to(DEVICE), tgt.to(DEVICE)
        tgt_in  = tgt[:, :-1]
        tgt_out = tgt[:, 1:]
        logits = model(src, tgt_in)
        loss = criterion(logits.reshape(-1, logits.size(-1)), tgt_out.reshape(-1))
        total_loss += loss.item()
    return total_loss / len(loader)


def train_model(model, train_loader, val_loader, n_epochs, save_path,
                lr=0.0005, patience=5):
    """Train with Adam optimiser and save best checkpoint by validation loss."""
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss(ignore_index=PAD_IDX)

    best_val_loss = float('inf')
    history = {'train': [], 'val': []}
    no_improve = 0

    for epoch in range(1, n_epochs + 1):
        t0 = time.time()
        train_loss = train_epoch(model, train_loader, optimizer, criterion)
        val_loss   = eval_epoch(model, val_loader, criterion)
        elapsed    = time.time() - t0

        history['train'].append(train_loss)
        history['val'].append(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), save_path)
            flag = '  ← best'
            no_improve = 0
        else:
            flag = ''
            no_improve += 1

        print(f"Epoch {epoch:3d}/{n_epochs} | "
              f"train {train_loss:.4f} | val {val_loss:.4f} | "
              f"{elapsed:.1f}s{flag}")

        if no_improve >= patience:
            print(f"Early stopping (no improvement for {patience} epochs)")
            break

    return history

print("✓ Training functions defined")

# PRETRAIN on CMUDict — general English
# Paper uses 100 epochs; we use fewer here due to Colab time limits.
# Increase PRETRAIN_EPOCHS to 100 for a more faithful replication.

PRETRAIN_EPOCHS = 20  # increase to 100 for full replication
Path('checkpoints').mkdir(exist_ok=True)

if os.path.exists('checkpoints/pretrained_cmudict.pt'):
    print("✓ Pretrained checkpoint found — skipping pretraining.")
    model.load_state_dict(torch.load('checkpoints/pretrained_cmudict.pt', map_location=DEVICE))
else:
    print(f"Pretraining for {PRETRAIN_EPOCHS} epochs on CMUDict...")
    pretrain_history = train_model(
        model,
        pre_train_loader,
        pre_val_loader,
        n_epochs=PRETRAIN_EPOCHS,
        save_path='checkpoints/pretrained_cmudict.pt'
    )
    plt.figure(figsize=(8, 4))
    plt.plot(pretrain_history['train'], label='Train loss')
    plt.plot(pretrain_history['val'],   label='Val loss')
    plt.xlabel('Epoch'); plt.ylabel('Cross-entropy loss')
    plt.title('Pretraining on CMUDict (General English)')
    plt.legend(); plt.tight_layout(); plt.savefig('pretrain_curve.png', dpi=120)
    plt.show()
    print("✓ Pretraining complete. Best checkpoint: checkpoints/pretrained_cmudict.pt")

"""## Section 7: Fine-tune on Scientific Vocabulary

This is the core contribution: we take the pretrained general-English model and adapt it to scientific vocabulary.

Following the paper exactly: we **reinitialise** the phoneme embedding layer and the output FC layer, then fine-tune the whole model.
"""

def prepare_for_finetuning(pretrained_path, src_vocab_size, tgt_vocab_size):
    """
    Load a pretrained checkpoint and re-initialise the target-side layers.
    This implements Figure 1 from the paper:
      - Encoder weights:     LOADED from checkpoint (frozen knowledge)
      - Decoder weights:     LOADED from checkpoint
      - tgt_embedding:       RE-INITIALISED (new phoneme set)
      - fc_out:              RE-INITIALISED (new output size)
    """
    # Create fresh model with same vocab sizes
    ft_model = G2PTransformer(
        src_vocab_size=src_vocab_size,
        tgt_vocab_size=tgt_vocab_size,
    ).to(DEVICE)

    # Load pretrained weights
    state_dict = torch.load(pretrained_path, map_location=DEVICE)

    # Load all weights except the target-side output layers
    # (they may have different sizes if phoneme vocab changed)
    model_state = ft_model.state_dict()
    for key, val in state_dict.items():
        if key in model_state and model_state[key].shape == val.shape:
            model_state[key] = val
        else:
            print(f"  Re-initialising: {key} (shape mismatch or new layer)")

    ft_model.load_state_dict(model_state)
    return ft_model


FINETUNE_EPOCHS = 50

if os.path.exists('checkpoints/finetuned_scientific.pt'):
    print("✓ Fine-tuned checkpoint found — skipping fine-tuning.")
    ft_model = G2PTransformer(
        src_vocab_size=len(char_vocab),
        tgt_vocab_size=len(phoneme_vocab),
    ).to(DEVICE)
    ft_model.load_state_dict(torch.load('checkpoints/finetuned_scientific.pt', map_location=DEVICE))
else:
    print("Loading pretrained model and preparing for fine-tuning...")
    ft_model = prepare_for_finetuning(
        'checkpoints/pretrained_cmudict.pt',
        src_vocab_size=len(char_vocab),
        tgt_vocab_size=len(phoneme_vocab)
    )
    print("✓ Model ready for fine-tuning")
    print(f"Fine-tuning for {FINETUNE_EPOCHS} epochs on scientific vocabulary...")
    finetune_history = train_model(
        ft_model,
        ft_train_loader,
        ft_val_loader,
        n_epochs=FINETUNE_EPOCHS,
        save_path='checkpoints/finetuned_scientific.pt',
        lr=0.0005
    )
    plt.figure(figsize=(8, 4))
    plt.plot(finetune_history['train'], label='Train loss')
    plt.plot(finetune_history['val'],   label='Val loss')
    plt.xlabel('Epoch'); plt.ylabel('Cross-entropy loss')
    plt.title('Fine-tuning on Scientific Vocabulary')
    plt.legend(); plt.tight_layout(); plt.savefig('finetune_curve.png', dpi=120)
    plt.show()
    print("✓ Fine-tuning complete. Best checkpoint: checkpoints/finetuned_scientific.pt")

"""## Section 8: Evaluate — Phoneme Error Rate (PER)

**Phoneme Error Rate (PER)** is the standard metric for G2P systems.
It is computed as the edit distance (insertions + deletions + substitutions)
between predicted and ground-truth phoneme sequences, divided by the length of the ground truth.

Lower is better. The paper achieves ~2.5% PER on British English with transfer learning vs ~27% from scratch.
"""

@torch.no_grad()
def greedy_decode(model, src, max_len=MAX_SEQ_LEN):
    """
    Greedy decoding: at each step, pick the most probable next phoneme.
    Returns a list of phoneme index sequences (one per sample in batch).
    """
    model.eval()
    src = src.to(DEVICE)
    src_pad_mask = (src == PAD_IDX)
    memory = model.encode(src, src_key_padding_mask=src_pad_mask)

    batch_size = src.size(0)
    # Start with <sos>
    tgt = torch.full((batch_size, 1), SOS_IDX, dtype=torch.long, device=DEVICE)
    finished = torch.zeros(batch_size, dtype=torch.bool, device=DEVICE)

    for _ in range(max_len):
        tgt_mask = model.make_causal_mask(tgt.size(1))
        logits = model.decode(tgt, memory, tgt_mask=tgt_mask,
                               memory_key_padding_mask=src_pad_mask)
        next_token = logits[:, -1, :].argmax(dim=-1, keepdim=True)  # (B, 1)
        tgt = torch.cat([tgt, next_token], dim=1)
        finished |= (next_token.squeeze(-1) == EOS_IDX)
        if finished.all():
            break

    # Convert to lists, stripping SOS/EOS/PAD
    results = []
    for seq in tgt.cpu().tolist():
        clean = [t for t in seq if t not in (SOS_IDX, EOS_IDX, PAD_IDX)]
        results.append(clean)
    return results


def compute_per(model, test_pairs, char2idx, phoneme2idx, idx2phoneme, batch_size=64):
    """
    Compute Phoneme Error Rate on a test set.
    Uses dynamic programming (same as word error rate but on phonemes).
    """
    from jiwer import wer as _wer

    dataset = G2PDataset(test_pairs, char2idx, phoneme2idx)
    loader  = DataLoader(dataset, batch_size=batch_size, collate_fn=collate_fn)

    all_pred, all_ref = [], []

    for src, tgt in tqdm(loader, desc="Evaluating"):
        pred_seqs = greedy_decode(model, src)

        for pred_ids, tgt_ids in zip(pred_seqs, tgt.tolist()):
            pred_phonemes = [idx2phoneme.get(i, '<unk>') for i in pred_ids
                             if i not in (SOS_IDX, EOS_IDX, PAD_IDX)]
            ref_phonemes  = [idx2phoneme.get(i, '<unk>') for i in tgt_ids
                             if i not in (SOS_IDX, EOS_IDX, PAD_IDX)]

            if ref_phonemes:
                # jiwer expects strings; we join phonemes with spaces
                all_pred.append(' '.join(pred_phonemes))
                all_ref.append(' '.join(ref_phonemes))

    per = _wer(all_ref, all_pred) * 100  # jiwer WER = PER when tokens are phonemes
    return per, all_pred, all_ref


print("✓ Evaluation functions defined")

# Build CMUDict-only phoneme vocabulary so the pretrained checkpoint vocab size matches.
# Read the actual vocab size from the checkpoint rather than hardcoding it.
all_cmu_phonemes_set = set()
for ipa_seq in cmu_ipa_dict.values():
    all_cmu_phonemes_set.update(ipa_seq.split())

_pretrain_ckpt = torch.load('checkpoints/pretrained_cmudict.pt', map_location=DEVICE)
_pretrain_tgt_vocab_size = _pretrain_ckpt['tgt_embedding.weight'].shape[0]
_n_unique = _pretrain_tgt_vocab_size - len(SPECIAL_TOKENS)

sorted_cmu_phonemes = sorted(list(all_cmu_phonemes_set))
cmu_only_phoneme_vocab = SPECIAL_TOKENS + sorted_cmu_phonemes[:_n_unique]
cmu_only_phoneme2idx = {t: i for i, t in enumerate(cmu_only_phoneme_vocab)}
cmu_only_idx2phoneme = {i: t for t, i in cmu_only_phoneme2idx.items()}

print(f"Original unique phonemes from cmu_ipa_dict: {len(all_cmu_phonemes_set)}")
print(f"Phoneme vocabulary size from checkpoint: {_pretrain_tgt_vocab_size}")
assert len(cmu_only_phoneme_vocab) == _pretrain_tgt_vocab_size, \
    f"Vocab size mismatch: built {len(cmu_only_phoneme_vocab)}, checkpoint expects {_pretrain_tgt_vocab_size}"

# Load best checkpoints and evaluate both models

# Instantiate a new model with the vocab size read from the checkpoint.
pretrain_eval_model = G2PTransformer(
    src_vocab_size=len(char_vocab),
    tgt_vocab_size=_pretrain_tgt_vocab_size,
).to(DEVICE)

# --- Pretrained (general English) model on scientific test set ---
pretrain_eval_model.load_state_dict(_pretrain_ckpt)
print("Evaluating pretrained (CMUDict) model on scientific test set...")
# Use the cmu_only_phoneme2idx and cmu_only_idx2phoneme for computing PER for the pretrained model.
per_pretrain, _, _ = compute_per(pretrain_eval_model, ft_test, char2idx, cmu_only_phoneme2idx, cmu_only_idx2phoneme)
print(f"  Pretrained model PER (scientific): {per_pretrain:.3f}%")

# --- Fine-tuned (scientific) model on scientific test set ---
# The ft_model is already correctly instantiated with the combined vocab size (113).
ft_model.load_state_dict(torch.load('checkpoints/finetuned_scientific.pt', map_location=DEVICE))
print("\nEvaluating fine-tuned (scientific) model on scientific test set...")
# Use the combined phoneme2idx and idx2phoneme for computing PER for the fine-tuned model.
per_finetune, pred_samples, ref_samples = compute_per(
    ft_model, ft_test, char2idx, phoneme2idx, idx2phoneme)
print(f"  Fine-tuned model PER (scientific): {per_finetune:.3f}%")

print(f"\n{'='*50}")
print(f"  PER improvement: {per_pretrain - per_finetune:.3f} percentage points")
print(f"{'='*50}")

# Show some example predictions vs ground truth
print("Sample predictions (fine-tuned model):")
print(f"{'PREDICTED':<50} {'REFERENCE':<50}")
print("-" * 100)
for pred, ref in zip(pred_samples[:15], ref_samples[:15]):
    match = '✓' if pred == ref else '✗'
    print(f"{match} {pred:<48} {ref:<48}")

"""## Section 9: Inference — Test on Scientific Sentences

Now let's test the fine-tuned model on new scientific text, including edge cases like IUPAC names and made-up scientific words.
"""

def predict_sentence(model, sentence, char2idx, idx2phoneme, max_len=MAX_SEQ_LEN):
    """Convert a sentence string to its predicted IPA phoneme sequence."""
    sentence = sentence.lower()
    words = re.findall(r'[a-zA-Z]+', sentence)

    # Encode
    g_ids = [char2idx.get(c, UNK_IDX) for c in ' '.join(words)]
    g_ids = [SOS_IDX] + g_ids[:max_len-2] + [EOS_IDX]
    src = torch.tensor([g_ids], dtype=torch.long)

    # Decode
    pred_ids = greedy_decode(model, src)[0]
    phonemes = [idx2phoneme.get(i, '?') for i in pred_ids]
    return ' '.join(phonemes)


# Test sentences — from scientific domains
test_sentences = [
    # General science
    "The enzyme catalyses the hydrolysis of adenosine triphosphate.",
    "Thermodynamics governs the entropy of isolated systems.",
    # Physics / maths
    "The eigenvalue of the Hamiltonian operator determines the energy.",
    "Fourier transforms decompose signals into sinusoidal components.",
    # Chemistry
    "Dimethylsulfoxide is a polar aprotic solvent used in synthesis.",
    "The stoichiometry of the reaction favours the endothermic pathway.",
    # Edge cases — invented scientific-sounding words (like Jabberwocky in the paper)
    "The quarkinium bosonates through electrofluorescent wavicles.",
]

ft_model.load_state_dict(torch.load('checkpoints/finetuned_scientific.pt', map_location=DEVICE))

print("Fine-tuned model predictions:")
print("=" * 70)
for sent in test_sentences:
    ipa = predict_sentence(ft_model, sent, char2idx, idx2phoneme)
    print(f"INPUT:  {sent}")
    print(f"OUTPUT: {ipa}")
    print("-" * 70)

# Optional: Compare fine-tuned vs pretrained on the same sentences
# Load the pretrained model into the pretrain_eval_model instance, which has the correct vocab size.
pretrain_eval_model.load_state_dict(torch.load('checkpoints/pretrained_cmudict.pt', map_location=DEVICE))

print("Comparison: pretrained vs fine-tuned")
comparison_sentence = "The eigenvalue of the Hamiltonian determines thermodynamic entropy."

# Use pretrain_eval_model for the pretrained predictions, and its corresponding vocab
ipa_pretrained  = predict_sentence(pretrain_eval_model, comparison_sentence, char2idx, cmu_only_idx2phoneme)
ipa_finetuned   = predict_sentence(ft_model, comparison_sentence, char2idx, idx2phoneme)

print(f"Sentence:   {comparison_sentence}")
print(f"Pretrained: {ipa_pretrained}")
print(f"Fine-tuned: {ipa_finetuned}")

# Generate this evaluation sheet automatically
import csv

eval_words = [
    "photosynthesis", "eigenvalue", "methylpropanol",
    "deoxyribonucleic", "thermodynamics", "stoichiometry",
    "tetrahydrofuran", "hamiltonian", "chromatography",
    "phenylalanine", "electromagnetism", "piezoelectric",
    "sinusoidal", "hydrolysis", "torque",
]

ft_model.load_state_dict(torch.load('checkpoints/finetuned_scientific.pt',
                                     map_location=DEVICE))

with open('human_eval.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['word', 'predicted_ipa', 'espeak_reference', 'correct?', 'notes'])
    for word in eval_words:
        predicted = predict_sentence(ft_model, word, char2idx, idx2phoneme)
        reference = sci_dictionary.get(word, 'N/A')
        writer.writerow([word, predicted, reference, '', ''])

print("✓ Saved human_eval.csv — open and fill in the 'correct?' column")

# Commented out IPython magic to ensure Python compatibility.
# %pwd

# ---------------------------------------------------------------------------
# File processing: parse_pdf.py output -> IPA-annotated .txt
# ---------------------------------------------------------------------------

def process_text_file(input_path: str, output_path: str, model, sci_dict: dict,
                      char2idx: dict, idx2phoneme: dict) -> None:
    """
    Read a TTS-ready plain-text file produced by parse_pdf.py, annotate
    scientific/technical words with predicted IPA, and write to output_path.

    Output format is compatible with ipa_speaker.py:
      - Words found in the scientific dictionary get a /IPA/ suffix from the dict.
      - Longer words (>=7 chars) not in the dict get a /IPA/ suffix from the model.
      - Short common words are left as plain text.

    Example output line:
      The eigenvalue /aɪɡənvæljuː/ of the Hamiltonian /hæmɪltoʊniən/ is determined by
    """
    lines = Path(input_path).read_text(encoding='utf-8').splitlines()
    model.eval()

    with open(output_path, 'w', encoding='utf-8') as f:
        for line in lines:
            if not line.strip():
                f.write('\n')
                continue

            # Split into alternating word / non-word tokens to preserve punctuation/spacing
            tokens = re.findall(r'[A-Za-z]+|[^A-Za-z]+', line)
            out_parts = []

            for tok in tokens:
                if not tok.isalpha():
                    out_parts.append(tok)
                    continue

                word_lower = tok.lower()

                # Only annotate words that are present in the scientific dictionary.
                # The model is used to generate the IPA for those words; words not
                # in the dictionary are left as plain text.
                if word_lower in sci_dict:
                    raw = predict_sentence(model, word_lower, char2idx, idx2phoneme)
                    ipa = ''.join(raw.split())
                    if ipa:
                        out_parts.append(f"/{ipa}/")
                    else:
                        out_parts.append(tok)
                else:
                    out_parts.append(tok)

            f.write(''.join(out_parts) + '\n')

    print(f"✓ IPA-annotated text written to: {output_path}")


# Parse --input / --output flags if provided (use parse_known_args so the
# notebook-style positional args from Colab do not cause errors).
import argparse as _ap
_p = _ap.ArgumentParser(add_help=False)
_p.add_argument('--input',  default=None, help='Path to parse_pdf.py output .txt')
_p.add_argument('--output', default=None, help='Path to write IPA-annotated .txt')
_cli, _ = _p.parse_known_args()

if _cli.input and _cli.output:
    print(f"\nProcessing {_cli.input} -> {_cli.output} ...")
    ft_model.load_state_dict(
        torch.load('checkpoints/finetuned_scientific.pt', map_location=DEVICE))
    process_text_file(_cli.input, _cli.output, ft_model, sci_dictionary,
                      char2idx, idx2phoneme)

"""## Next Steps

Now that you have a working prototype, here are the most impactful things to do next:

### Improve the dictionary (highest impact)
1. Open `data/scientific_dictionary.json` and manually correct the most common/important terms
2. Add more domain-specific terms to `SEED_SCIENTIFIC_TERMS` and re-run Section 2
3. For IUPAC chemistry specifically, consider using PubChem's REST API to get systematic names

### Improve training
4. Increase `PRETRAIN_EPOCHS` to 100 and `FINETUNE_EPOCHS` to 25–50
5. Experiment with dictionary sizes (1K, 3K, 5K, 10K) and plot PER vs size (Figure 2 from the paper)
6. Add a learning rate scheduler (cosine annealing or warm-up)

### Evaluate more rigorously
7. Collect a small human-verified test set (50–100 sentences) for gold-standard evaluation
8. Test on your actual TTS system and measure downstream speech quality (MOS or PESQ)

### Connect to TTS
9. The fine-tuned model's output (IPA) can be fed directly into Coqui TTS or ESPnet
10. Replace the default G2P backend in your TTS pipeline with this model's `predict_sentence()` function
"""